const String appName = 'FoodNet';
const String lang = 'vi';

const String let_comment = lang=='en'? 'Write a comment': 'Hãy nhận xét gì đó';
const String delete_success = lang=='en'? 'Deleted!': 'Đã xóa!';
const String sale_this_thing = lang=='en'? "Do you want to sale this good?":"Bạn có muốn bán sản phẩm này không?";
const String price_string = lang=='en'? "Price of each":"Giá cho mỗi đơn vị";
const String add_title = lang=='en'? "Add title":"Thêm tiêu đề";
const String add_description  = lang=='en'? "Add description":"Thêm mô tả";
const String None  = lang=='en'? "None":"Trống";
const String already_chosen = lang=='en'? "Chosen!":"Đã chọn!";
const String tag_string = lang=='en'? "Categories":"Các Tag";
const String popular_string = lang=='en'? "Popular":"Phổ biến";
const String my_post_string = lang=='en'? "My Post":"Bài đăng của tôi";
const String recommend_string = lang=='en'? "Recommend":"Đề xuất bởi FoodNet";
const String reviews_string = lang=='en'? "reviews":"đánh giá";
const String features_string = lang=='en'? "Features":"Đặc điểm";
const String name_string = lang=='en' ? "Name":"Tên";
const String description_string = lang=='en' ? "Description":"Mô tả";
const String friend_string = lang=='en'? "friends":"bạn bè";
const String logout_string = lang=='en'? "Log out":"Đăng xuất";
const String add_a_new_post = lang=='en'? "Add a new post":"Tạo một bài đăng mới";
const String upload_fail = lang=='en'? "Upload fail!":"Cập nhật thất bại!";
const String upload_success = lang=='en'? "Upload success!":"Cập nhật thành công!";
const String undefined_user = lang=='en'? "Undefined user":"Người dùng không xác định";
const String see_search_result_string = lang=='en'?"See search results for ":"Xem kết quả cho ";
const String recent_search_string = lang=='en'?"Recent search":"Tìm kiếm gần đây";
const String delete_all_string = lang=='en'?"Delete all":"Xoá tất cả";
const String result_string = lang=='en'?"Results":"Kết quả";
const String search_string = lang=='en'?"Search":"Tìm kiếm";
const String search_food_hint_string = lang=='en'?"Which food to eat?":"Bạn muốn ăn gì?";
const String current_string = ".đ";
const String uploading_string = lang=='en'?'Uploading....':'Đang tải lên...';
const String my_favorite_string = lang=='en'?'Favorite':'Yêu thích';
const String message_string = lang=='en'?"Message":"Tin nhắn";
const String add2cart_string = lang=='en'?"Add to Cart":"Thêm vào giỏ hàng";
const String developing_option_string = lang=='en'?"Function is being developed!":"Tính năng đang được phát triển!";
const String total_string = lang=='en'?"Total":"Tổng";
String introductionString = lang=='en'?'Introduction ' : 'Giới thiệu ';
const String worksString = lang=='en'?'Works ':'Công việc ';
const String addWorkString = lang=='en'?'Add Work':'Thêm công việc';
const String worksAtString = lang=='en'?'Works at ':'Làm việc tại ';
const String noInfoString = lang=='en'?'There is no information to show':"Không có thông tin để hiển thị";
const String educationString = lang=='en'?'Education ':"Học vấn ";
const String addEducationString = lang=='en'?'Add Education':"Thêm trường học";
const String studyAtString = lang=='en'?'Studies at ':'Học tại ';
const String locationString = lang=='en'?'Place lived  ':"Nơi sống ";
const String addPlaceString = lang=='en'?'Add Place':"Thêm nơi sống";
const String liveAtString = lang=='en'?'Live at ':'Đến từ ';
const String basicInfoString = lang=='en'?'Basic info ':"Thông tin cơ bản ";
const String genderString = lang=='en'?'Gender ':"Giới tính ";
const String addGenderString = lang=='en'?'Add Gender':"Thêm giới tính";
const String favoriteString = lang=='en'?'Favorite ':"Sở thích ";
const String addFavoriteString = lang=='en'?'Add Favorite':"Thêm sở thích";
const String editProfileString = lang=='en'?'Edit profile':"Chỉnh sửa trang cá nhân";
const String addFriendString = lang=='en'?'Add Friend':"Thêm bạn bè";
const String friendString = lang=='en'?'Friends':"Bạn bè";
const String messageString = lang=='en'?'Message':"Nhắn tin";
const String viewInfoString = lang=='en'?'See Info of ':"Xem thông tin giới thiệu của ";
const String viewAllFriendsString = lang=='en'?'See all friends':"Xem tất cả bạn bè";
const String dayOfBirthString = lang=='en'?'Birthday ':'Sinh nhật ';
const String noInformationString = lang=='en'?'There is no information':'Chưa có thông tin';
const String addString = lang=='en'?'Add':'Thêm';
const String saveString = lang=='en'?'Save':'Lưu';
const String defaultBirthdayString = '1990-01-01';
const String defaultGender = lang=='en'?'Gender':'Giới tính';
const String maleString = lang=='en'?'Male':'Nam';
const String femaleString = lang=='en'?'Female':"Nữ";
const String differentString = lang=='en'?'Others':"Khác";
const String viewProfilePictureString = lang=='en'?'View Profile Picture':"Xem ảnh đại diện";
const String selectProfilePictureString = lang=='en'?'Select profile picture':"Chọn ảnh đại diện";
const String seeCoverPhotoString = lang=='en'?'See cover photo':"Xem ảnh bìa";
const String uploadCoverPhotoString = lang=='en'?'Upload cover photo':"Chọn ảnh bìa";
const String searchUserString = lang=='en'?'Search User':"Tìm kiếm người dùng";
const String searchConversation = lang=='en'?'Search Conversation':"Tìm kiếm cuộc trò chuyện";
const String searchFriendString = lang=='en'?'Search Friend':'Tìm kiếm bạn bè';
const String friendInvitation = lang=='en'?'Friend Requests':"Lời mời kết bạn";
const String suggestionString = lang=='en'?'Suggestions':"Gợi ý";
const String friendMayKnowString = lang=='en'?'People You May Know':"Những người bạn có thể biết";
const String mutualismFriendString = lang=='en'?'mutual friends':"bạn chung";
const String confirmString = lang=='en'?'Confirm':"Xác nhận";
const String deleteString = lang=='en'?'Delete':"Xoá";
const String sayHiString = lang=='en'?'  Say Hi':"  Gửi lời chào";
const String requestSentString = lang=='en'?'Request sent':"Đã gửi yêu cầu";
const String sentMessageString = lang=='en'?'Message ':"Nhắn tin cho ";
const String unFriendString = lang=='en'?'Unfriend ':"Huỷ kết bạn với ";
const String postString = lang=='en'? "Post":"Bài đăng";
const String cancelRequestString = lang=='en' ? "Cancel Request":"Huỷ yêu cầu";
const String acceptString = lang=='en'?"Accept":"Chấp nhận";
const String notValidString = lang=='en'?"Not valid!":"Không hợp lệ!";
const String loading_string = lang=='en'?"Loading...":"Đang tải...";
const String homePageString = lang=='en'?"Homepage":"Trang chủ";
const String editPostString = lang=='en'?"Edit Post":"Chỉnh sửa bài đăng";
const String forgotPassword = lang=='en'?"Forgot Password?":"Quên mật khẩu?";
const String registerString = lang=='en'?"Register":"Đăng ký";
const String account = lang=='en'?"Don't have account? ":"Chưa có tài khoản? ";
const String haveAccount = lang=='en'?'Already have an account? ':"Đã có tài khoản? ";
const String loginString = lang=='en'?'Login':"Đăng nhập";
const String discoveryString = lang=='en'?'Discovery':"Khám phá";
const String noUserFoundString = lang=='en'?'No user found for that email.':'Email chưa được đăng ký.';
const String wrongPassString = lang=='en'?'Wrong password provided for that user.':'Sai mật khẩu.';
const String weakPassString = lang=='en'?'The password provided is too weak.':'Mật khẩu quá yếu.';
const String emailExistString = lang=='en'?'The account already exists for that email.':'Email đã tồn tại.';
const String resetPassString = lang=='en'?'Password reset email was sent':'Yêu cầu đặt lại mật khẩu đã được gửi.';
const String passwordString = lang=='en'?'Password':"Mật khẩu";